"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

# pylint: disable=duplicate-code

from os import environ
from pathlib import Path

# Load environment file.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!

CONTRIBUTION_DIRECTORY = "/srv/cosmae/contributions"


###################################################################
# SECURITY WARNING: keep the secret key used in production secret!
# PLEASE add your own secret.
@property
def SECRET_KEY():  # pylint: disable=invalid-name
    "Get the secret key from environment."
    return get_docker_compose_secret("cosmae_django_key")


def get_docker_compose_secret(secret_name):
    "Get secret as provided by docker_compose"
    env_var_name = secret_name.upper()
    key = environ.get(env_var_name)
    if key is None:
        raise Exception(  # pylint: disable=broad-exception-raised
            f"Please set the {secret_name} secret."
        )
    return key


###################################################################
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "cosmae-poc.duckdns.org"]


CORS_ALLOWED_ORIGINS = []

SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "corsheaders",
    "django_rq",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.saml",
    "allauth.headless",
    "cosmae",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "django_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_docker_compose_secret("cosmae_db_name"),
        "USER": get_docker_compose_secret("cosmae_db_user"),
        "PASSWORD": get_docker_compose_secret("cosmae_db_password"),
        "HOST": "cosmae_db",
        "PORT": "5432",
        # "OPTIONS": {
        # "service": "cosmae_service",
        # "passfile": "/run/secrets/pgconf",
        # },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "/var/www/cosmae-poc.duckdns.org/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "cosmae.CosmaeUser"

RQ_QUEUES = {
    "default": {
        "HOST": "localhost",
        "PORT": get_docker_compose_secret("cosmae_redis_port"),
        "DB": 0,
        "DEFAULT_TIMEOUT": 360,
        "PASSWORD": get_docker_compose_secret("cosmae_redis_password"),
    }
}


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://cosmae_redis:6379",
        "OPTIONS": {"password": get_docker_compose_secret("cosmae_redis_password")},
    },
    "tag_definition_name_paths": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://cosmae_redis:6379",
        "OPTIONS": {"password": get_docker_compose_secret("cosmae_redis_password")},
        "KEY_PREFIX": "tag_definition_name_path",
    },
    "entity_display_txt_information": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://cosmae_redis:6379",
        "OPTIONS": {"password": get_docker_compose_secret("cosmae_redis_password")},
        "KEY_PREFIX": "entity_display_txt_information",
    },
}

IS_UNITTEST = True

ORCID_CLIENT_ID = get_docker_compose_secret("orcid_client_id")
ORCID_CLIENT_SECRET = get_docker_compose_secret("orcid_client_secret")


LOGGING = {
    "version": 1,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {},
    # "root": {
    #     "level": "DEBUG",
    #     "handlers": ["console"],
    # },
}

HEADLESS_ONLY = False
SOCIALACCOUNT_ADAPTER = "cosmae.user.adapter.CosmaeSocialAccountAdapter"
ACCOUNT_ADAPTER = "cosmae.user.adapter.CosmaeAccountAdapter"
SOCIALACCOUNT_ONLY = True
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_PROVIDERS = {
    "saml": {
        # Here, each app represents the SAML provider configuration of one
        # organization.
        "APPS": [
            {
                # Used for display purposes, e.g. over by: {% get_providers %}
                "name": "CoSMAE",
                # Accounts signed up via this provider will have their
                # `SocialAccount.provider` value set to this ID. The combination
                # of this value and the `uid` must be unique. The IdP entity ID is a
                # good choice for this.
                "provider_id": "urn:example.com",
                # The organization slug is configured by setting the
                # `client_id` value. In this example, the SAML login URL is:
                #
                #     /accounts/saml/{client_id}/login/
                "client_id": "cosmae",
                # The fields above are common `SocialApp` fields. For SAML,
                # additional configuration is needed, which is placed in
                # `SocialApp.settings`:
                "settings": {
                    # Mapping account attributes to upstream (IdP specific) attributes.
                    # If left empty, an attempt will be done to map the attributes using
                    # built-in defaults.
                    "attribute_mapping": {
                        "uid": [
                            "urn:oasis:names:tc:SAML:attribute:subject-id",
                        ],
                        "email": ["urn:oid:1.2.840.113549.1.9.1"],
                        "email_verified": [
                            "emailVerified",
                            "http://schemas.auth0.com/email_verified",
                        ],
                        "first_name": [
                            "urn:oid:2.5.4.42",
                        ],
                        "last_name": [
                            "urn:oid:2.5.4.4",
                        ],
                        "username": [
                            "http://schemas.auth0.com/nickname",
                        ],
                    },
                    # The following setting allows you to force the use of nameID as email.
                    # This can be useful if you are using a SAML IdP that is broken in some way and
                    # does not allow use of the emailAddress nameid format
                    "use_nameid_for_email": False,
                    # The configuration of the IdP.
                    "idp": {
                        # The entity ID of the IdP is required.
                        "entity_id": "http://127.0.0.1/realms/CoSMAE",
                        # Then, you can either specify the IdP's metadata URL:
                        "metadata_url": "http://127.0.0.1/realms/CoSMAE/protocol/saml/descriptor",
                        # for testing purposes only
                        "metadata_cache_timeout": 0,
                    },
                    # The configuration of the SP.
                    "sp": {
                        # Optional entity ID of the SP. If not set,
                        #  defaults to the `saml_metadata` urlpattern
                        # "entity_id": "https://serviceprovider.com/sso/sp/metadata.xml",
                    },
                    # Advanced settings.
                    "advanced": {
                        "allow_repeat_attribute_name": True,
                        "allow_single_label_domains": False,
                        "authn_request_signed": False,
                        "digest_algorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
                        "logout_request_signed": False,
                        "logout_response_signed": False,
                        "metadata_signed": False,
                        "name_id_encrypted": False,
                        "name_id_format": "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
                        "private_key": get_docker_compose_secret(
                            "saml_client_private_key"
                        ),
                        "reject_deprecated_algorithm": True,
                        # Due to security concerns, IdP initiated SSO is rejected by default.
                        "reject_idp_initiated_sso": True,
                        "signature_algorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
                        "want_assertion_encrypted": False,
                        "want_assertion_signed": False,
                        "want_attribute_statement": True,
                        "want_message_signed": False,
                        "want_name_id": False,
                        "want_name_id_encrypted": False,
                        # "x509cert": get_file_secret("saml_client_certificate"),
                    },
                    "contact_person": {
                        "technical": {
                            "givenName": "Alice",
                            "emailAddress": "alice@example.com",
                        },
                        "administrative": {
                            "givenName": "Bob",
                            "emailAddress": "bob@example.com",
                        },
                    },
                },
            },
        ],
        "SCOPES": ["emailVerified"],
    }
}
