"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

# pylint: disable=duplicate-code

from os import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
DOMAIN_NAME = "http://127.0.0.1:5173"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True


CONTRIBUTION_DIRECTORY = "/srv/cosmae/contributions"

###################################################################
# SECURITY WARNING: keep the secret key used in production secret!
# PLEASE add your own secret.


@property
def SECRET_KEY():  # pylint: disable=invalid-name
    "Get the secret key from environment."
    return get_file_secret("cosmae_django_key")


def get_file_secret(secret_name):
    "Get secret as provided by docker_compose"
    try:
        with open(
            f"{BASE_DIR.absolute()}/.secrets_local/{secret_name}", encoding="utf-8"
        ) as key_file:
            key = key_file.readline().rstrip("\n")
    except FileNotFoundError:
        env_var_name = secret_name.upper()
        key = environ.get(env_var_name)
    if not key:
        raise Exception(  # pylint: disable=broad-exception-raised
            f"Please set the {secret_name} secret."
        )
    return key


###################################################################
ALLOWED_HOSTS = []

CORS_ALLOWED_ORIGINS = ["http://127.0.0.1:5173", "http://localhost:5173"]

SILENCED_SYSTEM_CHECKS = ["corsheaders.E001", "corsheaders.E003"]


CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "Content-Type",
    "Access-Control-Allow-Credentials",
    "Access-Control-Allow-Origin",
    "X-CSRFToken",
]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = False
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:5173"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "corsheaders",
    "django_rq",
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.mfa",
    "cosmae",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "django_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_file_secret("cosmae_db_name"),
        "USER": get_file_secret("cosmae_db_user"),
        "PASSWORD": get_file_secret("cosmae_db_password"),
        "HOST": "127.0.0.1",
        "PORT": "5444",
    }
}

PASSWORD_HASHERS = [
    "cosmae.util.password_hasher.MkPasswordYescryptPasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "cosmae.CosmaeUser"

RQ_QUEUES = {
    "default": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 0,
        "DEFAULT_TIMEOUT": 360,
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://localhost:6379",
    },
    "tag_definition_name_paths": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://localhost:6379",
        "KEY_PREFIX": "tag_definition_name_path",
    },
    "entity_display_txt_information": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://localhost:6379",
        "KEY_PREFIX": "entity_display_txt_information",
    },
}

HOST_PIPE_PATH = "/srv/cosmae/user_pipe"

IS_UNITTEST = False
ACCOUNT_RATE_LIMITS = False

ORCID_CLIENT_ID = get_file_secret("orcid_client_id")
ORCID_CLIENT_SECRET = get_file_secret("orcid_client_secret")

HEADLESS_ONLY = True
SOCIALACCOUNT_ADAPTER = "cosmae.user.adapter.CosmaeSocialAccountAdapter"
SOCIALACCOUNT_ENABLED = False
ACCOUNT_ADAPTER = "cosmae.user.adapter.CosmaeAccountAdapter"
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SIGNUP_FORM_CLASS = "cosmae.user.forms.CosmaeSignupForm"

HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": DOMAIN_NAME + "/account/verify-email/{key}",
    "account_signup": DOMAIN_NAME,
    "password_reset_url": DOMAIN_NAME,
    # Key placeholders are automatically populated. You are free to adjust this
    # to your own needs, e.g.
    #
    # "https://app.project.org/account/email/verify-email?token={key}",
    #     "account_reset_password": "https://app.project.org/account/password/reset",
    #     "account_reset_password_from_key":
    #         "https://app.project.org/account/password/reset/key/{key}",
    #     "account_signup": "https://app.project.org/account/signup",
    #     # Fallback in case the state containing the `next` URL is lost and the handshake
    #     # with the third-party provider fails.
    #     "socialaccount_login_error": "https://app.project.org/account/provider/callback",
}

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = get_file_secret("email_host_user")
EMAIL_HOST_PASSWORD = get_file_secret("email_app_password")
