version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/ui"
  - package-ecosystem: "pip"
    directories:
      - "/"
  - package-ecosystem: "docker"
    directories:
      - "/container"
