secrets:
  cosmae_db_password:
    external: true
  cosmae_db_user:
    external: true
  cosmae_db_name:
    external: true
  cosmae_django_key:
    external: true
  cosmae_redis_password:
    external: true
  cosmae_redis_conf:
    external: true
volumes:
  cosmae_db_volume:
  cosmae_redis_volume:

services:
  cosmae_ui:
    build:
      context: ./
      dockerfile: container/ui_dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/cosmae/ssl:/etc/ssl:ro
      - /srv/cosmae/acme-challenge:/srv/acme-challenge
      - /etc/localtime:/etc/localtime:ro
    image: 127.0.0.1:5000/cosmae_ui
    # command: [nginx-debug, '-g', 'daemon off;']

  cosmae_queue_worker:
    build:
      context: ./
      dockerfile: container/django_dockerfile
    restart: unless-stopped
    secrets:
      - cosmae_django_key
      - cosmae_db_name
      - cosmae_db_user
      - cosmae_db_password
      - cosmae_redis_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
    image: 127.0.0.1:5000/cosmae_django
    command: [
      "python",
      "manage.py",
      "rqworker",
      "--with-scheduler"
    ]

  cosmae_django:
    build:
      context: ./
      dockerfile: container/django_dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    expose:
      - 8000
    secrets:
      - cosmae_django_key
      - cosmae_db_name
      - cosmae_db_user
      - cosmae_db_password
      - cosmae_redis_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
    image: 127.0.0.1:5000/cosmae_django
    # command: [
    #   'gunicorn',
    #   'django_project.asgi:application',
    #   '-k',
    #   'uvicorn.workers.UvicornWorker',
    #   '-b 0.0.0.0:8000',
    #   '--log-level',
    #   'debug'
    # ]

  cosmae_db:
    container_name: cosmae_db
    image: postgres:15.2
    shm_size: 265m
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    expose:
      - 5432
    environment:
    - POSTGRES_PASSWORD_FILE=/run/secrets/cosmae_db_password
    - POSTGRES_USER_FILE=/run/secrets/cosmae_db_user
    - POSTGRES_DB_FILE=/run/secrets/cosmae_db_name
    secrets:
    - cosmae_db_password
    - cosmae_db_user
    - cosmae_db_name
    volumes:
<<<<<<< HEAD
    - cosmae_db_volume:/var/lib/postgresql/data
=======
    - cosmae_db_volume:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
>>>>>>> 066cac83 (Update container and configurations for inital deployment)

  cosmae_redis:
    container_name: cosmae_redis
    image: redis:7.0-alpine
    expose:
      - 6379
    volumes:
      - cosmae_redis_volume:/data
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - cosmae_redis_conf
    command: [
      "redis-server",
      "/var/run/secrets/cosmae_redis_conf"
    ]
    restart: unless-stopped
