[tool.poetry]
name = "cosmae"
version = "0.1.0"
description = ""
authors = ["Moritz Fürneisen <m.fuerneisen@zbw.eu>"]
readme = "README.md"
packages = [{include = "cosmae"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
django = "^5.0.4"
django-ninja = "^1.1.0"
django-cors-headers = "^4.3.1"
pandas = "^2.0.1"
django-rq = "^2.10.1"
psycopg = "^3.1.9"
levenshtein = "^0.25.1"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
black = "*"
coverage = "*"
pdoc3 = "*"
pre-commit = "*"
isort = "*"
pylint = "*"
pytest-django = "^4.5.2"
requests = "^2.28.1"
python-dotenv = "^0.21.0"
pytest-redis = "^3.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
