# Generated by Django 5.0.4 on 2024-04-17 14:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import cosmae.versioned.models_django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_persistent", models.CharField(max_length=36)),
                ("written_by", models.CharField(max_length=36)),
                ("approved_by", models.CharField(max_length=36, null=True)),
                ("hidden", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("id_parent_persistent", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("INR", "inner"), ("FLT", "float"), ("STR", "string")],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("time_edit", models.DateTimeField()),
                ("curated", models.BooleanField(default=False)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TagInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_persistent", models.CharField(max_length=36)),
                ("written_by", models.CharField(max_length=36)),
                ("approved_by", models.CharField(max_length=36, null=True)),
                ("time_edit", models.DateTimeField()),
                ("hidden", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("id_entity_persistent", models.CharField(max_length=36)),
                ("id_tag_definition_persistent", models.TextField()),
                ("value", models.TextField(blank=True, null=True)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ConfigValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField(unique=True)),
                ("value", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="CosmaeUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("id_persistent", models.CharField(max_length=36, unique=True)),
                ("tag_definitions", models.JSONField(default=list)),
                (
                    "permission_group",
                    models.TextField(
                        choices=[
                            ("APLC", "applicant"),
                            ("READ", "reader"),
                            ("CNTR", "contributor"),
                            ("EDTR", "editor"),
                            ("COMM", "commissioner"),
                        ],
                        default="APLC",
                        max_length=4,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("relates_to", models.UUIDField()),
                ("timestamp", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContributionCandidate",
            fields=[
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("id_persistent", models.UUIDField(primary_key=True, serialize=False)),
                ("has_header", models.BooleanField()),
                ("file_name", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("UPLD", "uploaded"),
                            ("CLXT", "columns extracted"),
                            ("CLAS", "columns assigned"),
                            ("VLXT", "values extracted"),
                            ("NTMT", "entities matched"),
                            ("NTAS", "entities assigned"),
                            ("VLAS", "values assigned"),
                            ("MRGD", "merged"),
                        ],
                        max_length=4,
                    ),
                ),
                ("error_msg", models.TextField(blank=True, null=True)),
                ("error_trace", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_persistent", models.CharField(max_length=36)),
                ("written_by", models.CharField(max_length=36)),
                ("approved_by", models.CharField(max_length=36, null=True)),
                ("time_edit", models.DateTimeField()),
                ("hidden", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("proxy_name", models.TextField(default="person")),
                ("display_txt", models.TextField(blank=True, null=True)),
                (
                    "contribution_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.contributioncandidate",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cosmae.entity",
                        unique=True,
                    ),
                ),
            ],
            bases=(models.Model, cosmae.versioned.models_django.HistoryMixin),
        ),
        migrations.CreateModel(
            name="EntityDuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_origin_persistent", models.TextField()),
                ("id_destination_persistent", models.TextField()),
                (
                    "contribution_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.contributioncandidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntityMergeRequest",
            fields=[
                ("id_destination_persistent", models.TextField()),
                ("id_origin_persistent", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("id_persistent", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("OPN", "open"),
                            ("CNF", "conflicts"),
                            ("CLS", "closed"),
                            ("RSL", "resolved"),
                            ("MRG", "merged"),
                            ("ERR", "error"),
                        ],
                        default="OPN",
                        max_length=3,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OwnershipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_persistent", models.UUIDField(unique=True)),
                ("id_tag_definition_persistent", models.TextField()),
                (
                    "petitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagDefinitionContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("id_persistent", models.UUIDField()),
                (
                    "id_existing_persistent",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("index_in_file", models.IntegerField()),
                ("discard", models.BooleanField(default=True)),
                (
                    "contribution_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.contributioncandidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagDefinitionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_persistent", models.CharField(max_length=36)),
                ("written_by", models.CharField(max_length=36)),
                ("approved_by", models.CharField(max_length=36, null=True)),
                ("hidden", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("id_parent_persistent", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("INR", "inner"), ("FLT", "float"), ("STR", "string")],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("time_edit", models.DateTimeField()),
                ("curated", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cosmae.tagdefinitionhistory",
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, cosmae.versioned.models_django.HistoryMixin),
        ),
        migrations.CreateModel(
            name="TagInstanceContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                ("id_entity_persistent", models.TextField(blank=True, null=True)),
                ("line_idx", models.IntegerField()),
                ("discard", models.BooleanField(default=True)),
                (
                    "tag_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.tagdefinitioncontribution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagInstanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_persistent", models.CharField(max_length=36)),
                ("written_by", models.CharField(max_length=36)),
                ("approved_by", models.CharField(max_length=36, null=True)),
                ("time_edit", models.DateTimeField()),
                ("hidden", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("id_entity_persistent", models.CharField(max_length=36)),
                ("id_tag_definition_persistent", models.TextField()),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cosmae.taginstancehistory",
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, cosmae.versioned.models_django.HistoryMixin),
        ),
        migrations.CreateModel(
            name="EntityConflictResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replace", models.BooleanField(default=None, null=True)),
                (
                    "entity_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.entity",
                    ),
                ),
                (
                    "entity_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.entity",
                    ),
                ),
                (
                    "merge_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.entitymergerequest",
                    ),
                ),
                (
                    "tag_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.tagdefinitionhistory",
                    ),
                ),
                (
                    "tag_instance_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.taginstancehistory",
                    ),
                ),
                (
                    "tag_instance_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.taginstancehistory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagMergeRequest",
            fields=[
                ("id_destination_persistent", models.TextField()),
                ("id_origin_persistent", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("id_persistent", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("OPN", "open"),
                            ("CNF", "conflicts"),
                            ("CLS", "closed"),
                            ("RSL", "resolved"),
                            ("MRG", "merged"),
                            ("ERR", "error"),
                        ],
                        default="OPN",
                        max_length=3,
                    ),
                ),
                ("disable_origin_on_merge", models.BooleanField(default=False)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contribution_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.contributioncandidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagConflictResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replace", models.BooleanField(default=None, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.entity",
                    ),
                ),
                (
                    "tag_definition_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.tagdefinitionhistory",
                    ),
                ),
                (
                    "tag_definition_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.tagdefinitionhistory",
                    ),
                ),
                (
                    "tag_instance_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.taginstancehistory",
                    ),
                ),
                (
                    "tag_instance_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cosmae.taginstancehistory",
                    ),
                ),
                (
                    "merge_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.tagmergerequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["id_persistent"], name="cosmae_entity_id_pers_0f2b92_idx"
            ),
        ),
    ]
