# Generated by Django 5.0.4 on 2024-04-17 14:33

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0002_pgsql_trigram"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entity",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["display_txt"], name="cosmae_entity_display_a10986_gist"
            ),
        ),
    ]
