# Generated by Django 4.2.8 on 2024-01-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmae", "0003_entity_cosmae_entity_display_a10986_gist"),
    ]

    operations = [
        migrations.RunSQL(
            """
            create view "cosmae_taginstance" as (
                select *
                from (
                        select max("id") max_id
                        from cosmae_taginstancehistory vt
                        group by id_persistent
                    ) with_version
                    left join  (
                        select *
                        from cosmae_taginstancehistory vt1
                    ) without_version
                    on "with_version"."max_id"="without_version"."id"
            )""",
            reverse_sql="drop view cosmae_taginstance",
        ),
        migrations.RunSQL(
            """
            create view "cosmae_tagdefinition" as (
                select *
                from (
                        select max("id") max_id
                        from cosmae_tagdefinitionhistory vt
                        group by id_persistent
                    ) with_version
                    left join  (
                        select *
                        from cosmae_tagdefinitionhistory vt1
                    ) without_version
                    on "with_version"."max_id"="without_version"."id"
            )""",
            reverse_sql="drop view cosmae_tagdefinition",
        ),
    ]
