# Generated by Django 4.2.2 on 2023-12-07 13:24

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    "Migration for enabling postgres fuzzy string match"

    dependencies = [
        ("cosmae", "0004_tag_most_recent_views"),
    ]

    operations = [CreateExtension("fuzzystrmatch")]
