# Generated by Django 5.0.4 on 2024-05-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0005_fuzzy_string_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributioncandidate",
            name="empty_values",
            field=models.TextField(default="null,nan,na"),
        ),
    ]
