# Generated by Django 5.0.4 on 2024-06-05 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0006_contributioncandidate_empty_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityReason",
            fields=[
                ("id_entity_persistent", models.CharField(max_length=36)),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField()),
                (
                    "id_persistent",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
