# Generated by Django 5.0.4 on 2024-06-13 11:22

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0007_entityjustification"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entityjustification",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["text"], name="cosmae_entity_text_ce0667_gist"
            ),
        ),
    ]
