# Generated by Django 5.0.4 on 2024-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0008_entityjustification_cosmae_entity_text_ce0667_gist"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributioncandidate",
            name="justification",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
