# Generated by Django 5.0.4 on 2024-07-30 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0009_contributioncandidate_justification"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditSession",
            fields=[
                (
                    "id_persistent",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("id_owner_persistent", models.CharField(max_length=36)),
                ("name", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="cosmaeuser",
            name="edit_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="cosmae.editsession",
            ),
        ),
        migrations.CreateModel(
            name="EditSessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_participant",
                    models.CharField(
                        choices=[("INT", "internal"), ("ORC", "ORCID")], max_length=3
                    ),
                ),
                ("id_participant", models.CharField(max_length=36)),
                ("name_participant", models.TextField()),
                (
                    "edit_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.editsession",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="editsessionparticipant",
            constraint=models.UniqueConstraint(
                fields=("edit_session", "id_participant"),
                name="Unique Edit Session Membership",
            ),
        ),
    ]
