# Generated by Django 5.0.4 on 2024-07-04 11:30

from uuid import uuid4

from django.db import migrations


def create_and_set_initial_edit_session(apps, schema_editor):
    "Create default edit sessions"
    user_model = apps.get_model("cosmae", "cosmaeuser")
    session_model = apps.get_model("cosmae", "editsession")
    participant_model = apps.get_model("cosmae", "editsessionparticipant")
    db_alias = schema_editor.connection.alias
    for user in user_model.objects.using(db_alias).filter(is_superuser=False):
        session = session_model.objects.using(db_alias).create(
            id_persistent=str(uuid4()),
            id_owner_persistent=user.id_persistent,
            name="Default Edit Session",
        )
        user.edit_session = session
        session.save()
        user.save()
        participant = participant_model.objects.using(db_alias).create(
            edit_session_id=session.id_persistent,
            type_participant="INT",
            id_participant=user.id_persistent,
            name_participant=user.username,
        )
        participant.save()


def reverse(app, schema_editor):  # pylint: disable=unused-argument
    "empty reverse migration"


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0010_editsession_cosmaeuser_edit_session_and_more"),
    ]

    operations = [
        migrations.RunPython(create_and_set_initial_edit_session, reverse_code=reverse)
    ]
