# Generated by Django 5.1 on 2024-08-13 12:11

import django.db.models.deletion
from django.db import migrations, models

from cosmae.versioned.view_sql import (
    CREATE_TAG_DEFINITION_VIEW_SQL,
    CREATE_TAG_INSTANCE_VIEW_SQL,
    DROP_TAG_DEFINITION_VIEW_SQL,
    DROP_TAG_INSTANCE_VIEW_SQL,
)

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# cosmae.migrations.0014_set_written_by_session

history_names = ["taginstancehistory", "tagdefinitionhistory", "entity"]


def create_and_set_initial_edit_session(apps, schema_editor):
    "Use the default edit session of the current written_by user"
    user_model = apps.get_model("cosmae", "cosmaeuser")
    db_alias = schema_editor.connection.alias
    for model_name in history_names:
        model = apps.get_model("cosmae", model_name)
        for instance in model.objects.using(db_alias).all():
            session = (
                user_model.objects.using(db_alias)
                .filter(id_persistent=instance.written_by)
                .get()
                .edit_session
            )
            instance.written_by_session_id = session.id_persistent
            instance.save()


def reverse_create_and_set_initial_edit_session(apps, schema_editor):
    "Use the owner of the written_by_session as the written_by author"
    user_model = apps.get_model("cosmae", "cosmaeuser")
    db_alias = schema_editor.connection.alias
    for model_name in history_names:
        model = apps.get_model("cosmae", model_name)
        for instance in model.objects.using(db_alias).all():
            user = (
                user_model.objects.using(db_alias)
                .filter(id_persistent=instance.written_by_session.id_owner_persistent)
                .get()
            )
            instance.written_by = user.id_persistent
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0011_default_edit_session"),
    ]

    operations = [
        migrations.RunSQL(
            DROP_TAG_INSTANCE_VIEW_SQL, reverse_sql=CREATE_TAG_INSTANCE_VIEW_SQL
        ),
        migrations.RunSQL(
            DROP_TAG_DEFINITION_VIEW_SQL, reverse_sql=CREATE_TAG_DEFINITION_VIEW_SQL
        ),
        migrations.AddField(
            model_name="entity",
            name="written_by_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edits+",
                to="cosmae.editsession",
            ),
        ),
        migrations.AddField(
            model_name="tagdefinitionhistory",
            name="written_by_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edits+",
                to="cosmae.editsession",
            ),
        ),
        migrations.AddField(
            model_name="taginstancehistory",
            name="written_by_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edits+",
                to="cosmae.editsession",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="written_by",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="tagdefinitionhistory",
            name="written_by",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="taginstancehistory",
            name="written_by",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.RunPython(
            code=create_and_set_initial_edit_session,
            reverse_code=reverse_create_and_set_initial_edit_session,
        ),
        migrations.RemoveField(
            model_name="entity",
            name="written_by",
        ),
        migrations.RemoveField(
            model_name="tagdefinitionhistory",
            name="written_by",
        ),
        migrations.RemoveField(
            model_name="taginstancehistory",
            name="written_by",
        ),
        migrations.RunSQL(
            CREATE_TAG_INSTANCE_VIEW_SQL, reverse_sql=DROP_TAG_INSTANCE_VIEW_SQL
        ),
        migrations.RunSQL(
            CREATE_TAG_DEFINITION_VIEW_SQL, reverse_sql=DROP_TAG_DEFINITION_VIEW_SQL
        ),
    ]
