# Generated by Django 5.1 on 2024-08-21 07:39

from django.db import migrations, models

from cosmae.versioned.view_sql import (
    CREATE_TAG_INSTANCE_VIEW_SQL,
    DROP_TAG_INSTANCE_VIEW_SQL,
)


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0012_edit_sessions_for_authorship"),
    ]

    operations = [
        migrations.RunSQL(
            DROP_TAG_INSTANCE_VIEW_SQL, reverse_sql=CREATE_TAG_INSTANCE_VIEW_SQL
        ),
        migrations.AddField(
            model_name="entity",
            name="merged_from",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="taginstancehistory",
            name="merged_from",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.RunSQL(
            CREATE_TAG_INSTANCE_VIEW_SQL, reverse_sql=DROP_TAG_INSTANCE_VIEW_SQL
        ),
    ]
