# Generated by Django 5.1 on 2024-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0013_entity_merged_from_taginstancehistory_merged_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="configvalue",
            name="idx",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="configvalue",
            name="key",
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name="configvalue",
            constraint=models.UniqueConstraint(
                models.F("key"), models.F("idx"), name="list_constraint"
            ),
        ),
    ]
