# Generated by Django 5.1 on 2024-09-19 14:09

from django.db import migrations, models


def un_nest_list(apps, schema_editor):
    "Transform list representation to have index in schema"
    config_value_model = apps.get_model("cosmae", "configvalue")
    db_alias = schema_editor.connection.alias
    for value in config_value_model.objects.using(db_alias):
        if isinstance(value.value, list):
            for idx, element in enumerate(value.value):
                config_value_model.objects.using(db_alias).create(
                    idx=idx, key=value.key, value=element
                )
            value.delete()


def nest_list(apps, schema_editor):
    "Transform list representation to be contained in single entry."
    config_value_model = apps.get_model("cosmae", "configvalue")
    db_alias = schema_editor.connection.alias
    key_query = (
        config_value_model.objects.using(db_alias)
        .filter(idx__isnull=False)
        .values("key")
        .distinct()
    )
    for key_object in key_query:
        key = key_object["key"]
        values_query = config_value_model.objects.using(db_alias).filter(key=key)
        unsorted = [(value.idx, value.value) for value in values_query]
        values_query.delete()
        config_value_model.objects.create(
            key=key, value=[value[1] for value in sorted(unsorted)]
        )


def add_quotes(apps, schema_editor):
    "add_quotes to config values for reversing of json to text field change"
    config_value_model = apps.get_model("cosmae", "configvalue")
    db_alias = schema_editor.connection.alias
    for value in config_value_model.objects.using(db_alias):
        value.value = f'"{value.value}"'
        value.save()


def remove_quotes(apps, schema_editor):
    "remove quotes from config values that are strings."
    config_value_model = apps.get_model("cosmae", "configvalue")
    db_alias = schema_editor.connection.alias
    for value in config_value_model.objects.using(db_alias):
        if value.value[0] == '"' and value.value[-1] == '"':
            value.value = value.value.strip('"')
            value.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0014_configvalue_idx_alter_configvalue_key_and_more"),
    ]

    operations = [
        migrations.RunPython(un_nest_list, reverse_code=nest_list),
        migrations.AlterField(
            model_name="configvalue",
            name="value",
            field=models.TextField(),
        ),
        migrations.RunPython(remove_quotes, reverse_code=add_quotes),
    ]
