# Generated by Django 5.1 on 2024-09-23 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0015_config_value_list_refactor"),
    ]

    operations = [
        migrations.RenameModel("entity", "entityhistory"),
        migrations.RenameIndex(
            model_name="entityhistory",
            new_name="cosmae_entity_id_pers_9293fd_idx",
            old_name="cosmae_entity_id_pers_0f2b92_idx",
        ),
        migrations.RenameIndex(
            model_name="entityhistory",
            new_name="cosmae_entity_display_48e0ce_gist",
            old_name="cosmae_entity_display_a10986_gist",
        ),
        migrations.RemoveField(
            model_name="entityhistory",
            name="proxy_name",
        ),
        migrations.AlterField(
            model_name="entityconflictresolution",
            name="entity_destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cosmae.entityhistory",
            ),
        ),
        migrations.AlterField(
            model_name="entityconflictresolution",
            name="entity_origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cosmae.entityhistory",
            ),
        ),
        migrations.AlterField(
            model_name="tagconflictresolution",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cosmae.entityhistory",
            ),
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_persistent", models.CharField(max_length=36)),
                ("approved_by", models.CharField(max_length=36, null=True)),
                ("time_edit", models.DateTimeField()),
                ("hidden", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("display_txt", models.TextField(blank=True, null=True)),
                ("merged_from", models.CharField(max_length=36, null=True)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
