# Generated by Django 5.1 on 2024-09-23 07:16

from django.db import migrations

from cosmae.versioned.view_sql import CREATE_ENTITY_VIEW_SQL, DROP_ENTITY_VIEW_SQL


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0016_entityhistory_and_more"),
    ]

    operations = [
        migrations.RunSQL(CREATE_ENTITY_VIEW_SQL, reverse_sql=DROP_ENTITY_VIEW_SQL)
    ]
