# Generated by Django 5.1 on 2024-09-24 11:57

from django.db import migrations

from cosmae.index_query import (
    CREATE_ENTITY_DISPLAY_TXT_INDEX_QUERY,
    CREATE_VALUE_VALUE_INDEX_QUERY,
    DROP_ENTITY_DISPLAY_TXT_INDEX_QUERY,
    DROP_TAG_INSTANCE_VALUE_INDEX_QUERY,
)


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0017_create_entity_most_recent_view"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="entityhistory",
            name="cosmae_entity_display_48e0ce_gist",
        ),
        migrations.RunSQL(
            CREATE_ENTITY_DISPLAY_TXT_INDEX_QUERY,
            reverse_sql=DROP_ENTITY_DISPLAY_TXT_INDEX_QUERY,
        ),
        migrations.RunSQL(
            CREATE_VALUE_VALUE_INDEX_QUERY,
            reverse_sql=DROP_TAG_INSTANCE_VALUE_INDEX_QUERY,
        ),
    ]
