# Generated by Django 5.1.1 on 2024-10-02 11:28

from django.db import migrations, models


def inner_to_bool(apps, schema_editor):
    "Transform inner tags to bool type, as this is the new, correct name."
    tag_def_history_model = apps.get_model("cosmae", "tagdefinitionhistory")
    db_alias = schema_editor.connection.alias
    for tag_def in tag_def_history_model.objects.using(db_alias):
        if tag_def.type == "INR":
            tag_def.type = "BOL"
            tag_def.save()


def bool_to_inner(apps, schema_editor):
    "Transform bool tags to inner type to restore old name."
    tag_def_history_model = apps.get_model("cosmae", "tagdefinitionhistory")
    db_alias = schema_editor.connection.alias
    for tag_def in tag_def_history_model.objects.using(db_alias):
        if tag_def.type == "BOL":
            tag_def.type = "INR"
            tag_def.save()


def flatten_tag_structure(apps, schema_editor):
    "Make sure inner tags have no data"
    tag_def_history_model = apps.get_model("cosmae", "tagdefinitionhistory")
    db_alias = schema_editor.connection.alias
    for tag_def in tag_def_history_model.objects.using(db_alias):
        tag_def.id_parent_persistent = None
        tag_def.save()


def flatten_tag_structure_reverse_pass(_apps, _schema_editor):
    """This reverse transformation does nothing,
    as a valid tag structure after migration was also valid before."""


class Migration(migrations.Migration):
    "Add a new inner tag type that is used for structuring the tag tree."

    dependencies = [
        ("cosmae", "0018_change_entity_index_add_tag_instance_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagdefinitionhistory",
            name="type",
            field=models.CharField(
                choices=[
                    ("INR", "inner"),
                    ("BOL", "bool"),
                    ("FLT", "float"),
                    ("STR", "string"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
        migrations.RunPython(inner_to_bool, reverse_code=bool_to_inner),
        migrations.RunPython(
            flatten_tag_structure, reverse_code=flatten_tag_structure_reverse_pass
        ),
    ]
