# Generated by Django 5.1.1 on 2024-11-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0020_permission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entityconflictresolution",
            name="replace",
        ),
        migrations.RemoveField(
            model_name="tagconflictresolution",
            name="replace",
        ),
        migrations.AddField(
            model_name="entityconflictresolution",
            name="replacement_state",
            field=models.CharField(
                choices=[
                    ("KEEP", "keep existing"),
                    ("RPLC", "new value"),
                    ("VALU", "replacement value"),
                ],
                default=None,
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entityconflictresolution",
            name="replacement_value",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="tagconflictresolution",
            name="replacement_state",
            field=models.CharField(
                choices=[
                    ("KEEP", "keep existing"),
                    ("RPLC", "new value"),
                    ("VALU", "replacement value"),
                ],
                default=None,
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tagconflictresolution",
            name="replacement_value",
            field=models.TextField(default=None, null=True),
        ),
    ]
