# Generated by Django 5.1.3 on 2024-12-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0021_remove_entityconflictresolution_replace_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cosmaeuser",
            options={},
        ),
        migrations.AddField(
            model_name="cosmaeuser",
            name="social_provider",
            field=models.CharField(default="None", max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name="cosmaeuser",
            unique_together={("username", "social_provider")},
        ),
    ]
