# Generated by Django 5.1.4 on 2024-12-18 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0022_alter_cosmaeuser_options_cosmaeuser_social_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributioncandidate",
            name="edit_session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cosmae.editsession",
            ),
        ),
    ]
