# Generated by Django 5.1.4 on 2024-12-18 15:06

from django.db import migrations, models

from cosmae.index_query import (
    CREATE_VALUE_VALUE_INDEX_QUERY,
    DROP_TAG_INSTANCE_VALUE_INDEX_QUERY,
    DROP_VALUE_VALUE_INDEX_QUERY,
)
from cosmae.versioned.view_sql import (
    CREATE_COLUMN_VIEW_SQL,
    CREATE_TAG_DEFINITION_VIEW_SQL,
    CREATE_TAG_INSTANCE_VIEW_SQL,
    CREATE_VALUE_VIEW_SQL,
    DROP_COLUMN_VIEW_SQL,
    DROP_TAG_DEFINITION_VIEW_SQL,
    DROP_TAG_INSTANCE_VIEW_SQL,
    DROP_VALUE_VIEW_SQL,
)


class Migration(migrations.Migration):

    dependencies = [("cosmae", "0023_contributioncandidate_edit_session")]

    operations = [
        migrations.RunSQL(
            DROP_TAG_DEFINITION_VIEW_SQL, reverse_sql=CREATE_TAG_DEFINITION_VIEW_SQL
        ),
        migrations.RunSQL(
            DROP_TAG_INSTANCE_VIEW_SQL, reverse_sql=CREATE_TAG_INSTANCE_VIEW_SQL
        ),
        migrations.RunSQL(
            DROP_TAG_INSTANCE_VALUE_INDEX_QUERY,
            reverse_sql=CREATE_VALUE_VALUE_INDEX_QUERY,
        ),
        migrations.RenameModel("tagdefinition", "column"),
        migrations.RenameModel("tagdefinitionhistory", "columnhistory"),
        migrations.RenameModel("taginstance", "value"),
        migrations.RenameModel("taginstancehistory", "valuehistory"),
        migrations.RenameField(
            model_name="entityconflictresolution",
            old_name="tag_definition",
            new_name="column",
        ),
        migrations.RenameField(
            model_name="entityconflictresolution",
            old_name="tag_instance_destination",
            new_name="value_destination",
        ),
        migrations.RenameField(
            model_name="entityconflictresolution",
            old_name="tag_instance_origin",
            new_name="value_origin",
        ),
        migrations.RenameField(
            model_name="ownershiprequest",
            old_name="id_tag_definition_persistent",
            new_name="id_column_persistent",
        ),
        migrations.RenameField(
            model_name="tagconflictresolution",
            old_name="tag_definition_destination",
            new_name="column_destination",
        ),
        migrations.RenameField(
            model_name="tagconflictresolution",
            old_name="tag_definition_origin",
            new_name="column_origin",
        ),
        migrations.RenameField(
            model_name="tagconflictresolution",
            old_name="tag_instance_destination",
            new_name="value_destination",
        ),
        migrations.RenameField(
            model_name="tagconflictresolution",
            old_name="tag_instance_origin",
            new_name="value_origin",
        ),
        migrations.RenameField(
            model_name="valuehistory",
            old_name="id_tag_definition_persistent",
            new_name="id_column_persistent",
        ),
        migrations.AlterField(
            model_name="columnhistory",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="next_version+",
                to="cosmae.columnhistory",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="entityhistory",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="next_version+",
                to="cosmae.entityhistory",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="valuehistory",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="next_version+",
                to="cosmae.valuehistory",
                unique=True,
            ),
        ),
        migrations.RenameModel(
            old_name="TagMergeRequest",
            new_name="ColumnMergeRequest",
        ),
        migrations.RunSQL(
            CREATE_VALUE_VALUE_INDEX_QUERY, reverse_sql=DROP_VALUE_VALUE_INDEX_QUERY
        ),
        migrations.RunSQL(CREATE_COLUMN_VIEW_SQL, reverse_sql=DROP_COLUMN_VIEW_SQL),
        migrations.RunSQL(CREATE_VALUE_VIEW_SQL, reverse_sql=DROP_VALUE_VIEW_SQL),
    ]
