# Generated by Django 5.1.6 on 2025-05-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0024_rename_tag_models"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TagConflictResolution",
            new_name="ColumnConflictResolution",
        ),
        migrations.RenameField(
            model_name="cosmaeuser",
            old_name="tag_definitions",
            new_name="columns",
        ),
        migrations.RenameModel(
            old_name="TagDefinitionContribution",
            new_name="ColumnContribution",
        ),
        migrations.CreateModel(
            name="ValueContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                ("id_entity_persistent", models.TextField(blank=True, null=True)),
                ("line_idx", models.IntegerField()),
                ("discard", models.BooleanField(default=True)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.columncontribution",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TagInstanceContribution",
        ),
    ]
