# Generated by Django 5.2.1 on 2025-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0025_rename_tagconflictresolution_columnconflictresolution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cosmaeuser",
            name="password_changed",
            field=models.BooleanField(default=False),
        ),
    ]
