# Generated by Django 5.2.1 on 2025-06-06 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0026_cosmaeuser_password_changed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SshKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField()),
                ("name", models.TextField()),
                ("type", models.TextField()),
                ("id_persistent", models.CharField(max_length=36)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
