# Generated by Django 5.2.1 on 2025-07-31 13:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0027_sshkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnNamePathCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_path", models.JSONField()),
                ("name_path_string", models.TextField()),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.columnhistory",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        django.contrib.postgres.search.SearchVector("name_path_string"),
                        name="name_path_string_lower_idx",
                    )
                ],
            },
        ),
    ]
