# Generated by Django 5.2.1 on 2025-08-18 11:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


def most_recent(query_set):
    """Return the most recent version for all instances of a queryset."""
    # pylint: disable=no-member
    return query_set.filter(
        id=models.Subquery(
            query_set.filter(id_persistent=models.OuterRef("id_persistent"))
            .order_by(models.F("previous_version").desc(nulls_last=True))[:1]
            .values("id")
        )
    )


def populate_column_name_path_cache(apps, schema_editor):
    """Set column name path cache for all columns."""
    ColumnHistory = apps.get_model("cosmae", "ColumnHistory")

    for column in ColumnHistory.objects.all().order_by("time_edit"):
        store_column_name_path(apps, column, column.time_edit)


def store_column_name_path(apps, column, up_until):
    """Recursively set column name path cache."""
    ColumnNamePathCache = apps.get_model("cosmae", "ColumnNamePathCache")
    ColumnHistory = apps.get_model("cosmae", "ColumnHistory")
    if column.id_parent_persistent is None:
        parent_name_path = []
        most_recent_until = most_recent(ColumnHistory.objects.all())
    else:
        most_recent_until = most_recent(
            ColumnHistory.objects.filter(time_edit__lte=up_until)
        )
        parent_name_path = (
            most_recent_until.filter(id_persistent=column.id_parent_persistent)
            .annotate(
                name_path=models.Subquery(
                    ColumnNamePathCache.objects.filter(
                        column_id=models.OuterRef("id")
                    ).values("name_path")
                )
            )
            .values_list("name_path", flat=True)
            .get()
        )
    name_path = parent_name_path + [column.name]
    ColumnNamePathCache.objects.create(
        column_id=column.id,
        name_path=name_path,
        name_path_string=" -> ".join(name_path),
        time_edit=up_until,
    )
    for child in most_recent_until.filter(id_parent_persistent=column.id):
        store_column_name_path(apps, child, up_until)


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0027_sshkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnNamePathCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_path", models.JSONField()),
                ("name_path_string", models.TextField()),
                ("time_edit", models.DateTimeField()),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmae.columnhistory",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        django.contrib.postgres.search.SearchVector(
                            "name_path_string", config="english"
                        ),
                        name="name_path_string_lower_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(
            code=populate_column_name_path_cache,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
