# Generated by Django 5.2.1 on 2025-08-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0028_columnnamepathcache"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityduplicate",
            name="discard",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="entityduplicate",
            name="id_destination_persistent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
