# Generated by Django 5.2.8 on 2025-12-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0029_entityduplicate_discard_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPublication",
            fields=[
                (
                    "id_persistent",
                    models.CharField(
                        max_length=36, unique=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "step",
                    models.TextField(
                        choices=[
                            ("CREA", "Created"),
                            ("JUST", "Justification"),
                            ("DSPL", "DisplayText"),
                            ("CURA", "Curated"),
                            ("USER", "User"),
                            ("AUTH", "Authors"),
                            ("CMPL", "Completed"),
                        ],
                        default="CREA",
                        max_length=4,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                ("is_working", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DataPublicationStepInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.TextField(
                        choices=[
                            ("CREA", "Created"),
                            ("JUST", "Justification"),
                            ("DSPL", "DisplayText"),
                            ("CURA", "Curated"),
                            ("USER", "User"),
                            ("AUTH", "Authors"),
                            ("CMPL", "Completed"),
                        ],
                        max_length=4,
                    ),
                ),
                ("input", models.JSONField()),
            ],
        ),
        migrations.RenameIndex(
            model_name="entityhistory",
            new_name="cosmae_enti_id_pers_59dd9a_idx",
            old_name="cosmae_entity_id_pers_9293fd_idx",
        ),
        migrations.RenameIndex(
            model_name="entityjustification",
            new_name="cosmae_enti_text_80461e_gist",
            old_name="cosmae_entity_text_ce0667_gist",
        ),
        migrations.AddField(
            model_name="datapublicationstepinput",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="cosmae.datapublication",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datapublicationstepinput",
            unique_together={("publication", "step")},
        ),
    ]
