# Generated by Django 5.2.8 on 2026-01-15 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0030_datapublication_datapublicationstepinput_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityjustification",
            name="author_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cosmae.editsession",
            ),
        ),
    ]
