# Generated by Django 4.2.8 on 2024-01-03 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cosmae", "0030_taginstancehistory"),
    ]

    operations = [
        migrations.RunSQL(
            """
            create view "cosmae_taginstance" as (
                select id
                    , id_persistent
                    , id_entity_persistent
                    , id_tag_definition_persistent
                    , value
                    , time_edit
                    , previous_version_id
                from (
                        select max("id") max_id
                        from cosmae_taginstancehistory vt
                        group by id_persistent
                    ) with_version
                    left join  (
                        select *
                        from cosmae_taginstancehistory vt1
                    ) without_version
                    on "with_version"."max_id"="without_version"."id"
            )""",
            reverse_sql="drop view cosmae_taginstance",
        )
    ]
