# Generated by Django 6.0.5 on 2026-06-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0031_entityjustification_author_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributioncandidate",
            name="mark_delete",
            field=models.BooleanField(default=False),
        ),
    ]
