# Generated by Django 6.0.5 on 2026-07-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0032_contributioncandidate_mark_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="columnmergerequest",
            name="state",
            field=models.TextField(
                choices=[
                    ("CRT", "created"),
                    ("OPN", "open"),
                    ("CNF", "conflicts"),
                    ("CLS", "closed"),
                    ("RSL", "resolved"),
                    ("MRG", "merged"),
                    ("ERR", "error"),
                ],
                default="OPN",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="entitymergerequest",
            name="state",
            field=models.TextField(
                choices=[
                    ("CRT", "created"),
                    ("OPN", "open"),
                    ("CNF", "conflicts"),
                    ("CLS", "closed"),
                    ("RSL", "resolved"),
                    ("MRG", "merged"),
                    ("ERR", "error"),
                ],
                default="OPN",
                max_length=3,
            ),
        ),
    ]
