# Generated by Django 6.0.5 on 2026-08-12 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0033_alter_columnmergerequest_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="columnmergerequest",
            name="approved_by_session",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cosmae.editsession",
            ),
        ),
        migrations.AlterField(
            model_name="columnmergerequest",
            name="state",
            field=models.TextField(
                choices=[
                    ("CRT", "created"),
                    ("OPN", "open"),
                    ("CNF", "conflicts"),
                    ("CLS", "closed"),
                    ("RSL", "resolved"),
                    ("MRG", "merged"),
                    ("ERR", "error"),
                ],
                default="CRT",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="entitymergerequest",
            name="state",
            field=models.TextField(
                choices=[
                    ("CRT", "created"),
                    ("OPN", "open"),
                    ("CNF", "conflicts"),
                    ("CLS", "closed"),
                    ("RSL", "resolved"),
                    ("MRG", "merged"),
                    ("ERR", "error"),
                ],
                default="CRT",
                max_length=3,
            ),
        ),
    ]
