# Generated by Django 6.1 on 2026-08-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0034_columnmergerequest_approved_by_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitymergerequest",
            name="approved_by_session",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cosmae.editsession",
            ),
        ),
    ]
