# Generated by Django 6.1 on 2026-09-11 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("cosmae", "0036_alter_columnmergerequest_created_by_and_more"),
        ("cosmae", "0037_processrun"),
    ]

    dependencies = [
        ("cosmae", "0035_entitymergerequest_approved_by_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="columnmergerequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="entitymergerequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProcessRun",
            fields=[
                (
                    "id_persistent",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("process_name", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
