# Generated by Django 4.2.8 on 2024-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    create_view_query = """
            create view "cosmae_tagdefinition" as (
                select *
                from (
                        select max("id") max_id
                        from cosmae_tagdefinitionhistory vt
                        group by id_persistent
                    ) with_version
                    left join  (
                        select *
                        from cosmae_tagdefinitionhistory vt1
                    ) without_version
                    on "with_version"."max_id"="without_version"."id"
            )"""

    drop_view_query = "drop view cosmae_tagdefinition"

    dependencies = [
        ("cosmae", "0038_tagdefinitionhistory_disabled_and_more"),
    ]

    operations = [
        migrations.RunSQL(drop_view_query, reverse_sql=create_view_query),
        migrations.AddField(
            model_name="tagdefinitionhistory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL(create_view_query, reverse_sql=drop_view_query),
    ]
