# Generated by Django 4.2.8 on 2024-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmae", "0039_tagdefinitionhistory_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("relates_to", models.UUIDField()),
            ],
        ),
    ]
