"RAW queries for entity matching."

from cosmae.contribution.entity.match_queries.query_parts import (
    MATCHES_QUERY_STRING_WITHOUT_PAIRS,
    SCORED_CANDIDATE_PAIRS_PREFIX,
    SCORED_SINGLE_PAIR_PREFIX,
)

MATCHES_QUERY_STRING_CONTRIBUTION = (
    SCORED_CANDIDATE_PAIRS_PREFIX + MATCHES_QUERY_STRING_WITHOUT_PAIRS
)

MATCHES_QUERY_STRING_PAIR = (
    SCORED_SINGLE_PAIR_PREFIX + MATCHES_QUERY_STRING_WITHOUT_PAIRS
)
